# Generated by Django 6.0 on 2025-12-13 17:23

import assets.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('completed', 'Completed')], default='processing', max_length=20)),
                ('original_image', models.FileField(upload_to=assets.utils.get_original_upload_path)),
                ('processed_image', models.FileField(upload_to=assets.utils.get_processed_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
