# Generated by Django 6.0 on 2025-12-13 17:27

import assets.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='original_image',
            field=models.FileField(max_length=500, upload_to=assets.utils.get_original_upload_path),
        ),
        migrations.AlterField(
            model_name='asset',
            name='processed_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=assets.utils.get_processed_upload_path),
        ),
    ]
