# Generated by Django 6.0 on 2025-12-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_original_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='asset_metadata'),
        ),
    ]
