# Generated by Django 6.0 on 2025-12-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Asset metadata'),
        ),
    ]
